services:
  app:
    image: yoyo99828/filmpass
    container_name: filmpass
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: BQQIIGOqri7I7xdQYn0d
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: +1M+K6fjrubxyPDwED063Hiitce4RrWgCvcuCc+c44I=
      DB_URL: jdbc:mysql://filmpass-db.c38cw66kqirq.ap-northeast-2.rds.amazonaws.com:3306/filmpass
      DB_USERNAME: root
    depends_on:
      - mysql
      - redis
      - elasticsearch
    secrets:
      - FilmPass_DB
      - secret_key
    #restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - FilmPass_DB
    #restart: unless-stopped

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    #restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: es_server
    ports:
      - "9200:9200"
    environment:
      - node.name=es_server
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana_server
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es_server:9200
    depends_on:
      - elasticsearch
    #restart: unless-stopped

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper_server
    ports:
      - "2181:2181"
    volumes:
      - zk_data:/data
    #restart: unless-stopped

secrets:
  FilmPass_DB:
    file: ./secrets/FilmPass_DB.txt
  secret_key:
    file: ./secrets/secret_key.txt

volumes:
  mysql_data:
  redis_data:
  es_data:
  zk_data: