spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: FilmPass

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      jdbc:
        batch_size: 100

  data:
    redis:
      host: ${REDIS_HOST} #127.0.0.1
      port: ${REDIS_PORT} #6379
    web:
      pageable:
        max-page-size: 100
        one-indexed-parameters: false

  cache:
    type: redis

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}
