spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: FilmPass

  app:
    es:
     sync: true
     bootstrap: true   # Elasticsearch 초기화 사용

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    elasticsearch:
      uris: https://filmpasses.es.ap-northeast-2.aws.elastic-cloud.com
      username: elastic
      password: WBBvVFnb7jBailgswUMFv26r
      repositories:
        enabled: true

  cache:
    type: redis

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${JWT_SECRET_KEY}


